CREATE TABLE quests (
  quest_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  poster_id BIGINT NOT NULL REFERENCES users(user_id),
  title VARCHAR(50) NOT NULL,
  description TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
