// This file has been generated by Specta. Do not edit this file manually.
export type CreateQuestRequest = {
	title: string,
};

export type Quest = {
	questId: string,
	posterId: string,
	title: string,
	summary: string,
	details: string,
	status: QuestStatus,
	createdAt: string,
};

export type QuestStatus = "draft" | "ongoing" | "solved";

export type UpdateQuestRequest = {
	title?: string | null,
	summary?: string | null,
	details?: string | null,
	status?: QuestStatus | null,
};

export type User = {
	userId: string,
	githubId: string,
	handle: string,
	createdAt: string,
};
