// This file has been generated by Specta. Do not edit this file manually.
export type CreateQuestRequest = {
	title: string,
};

export type Quest = {
	questId: string,
	poster: User,
	title: string,
	summary: string,
	details: string,
	techs: string[],
	status: QuestStatus,
	createdAt: string,
};

export type QuestStatus = "draft" | "ongoing" | "solved";

export type SearchQuestParams = {
	query: string | null,
	techs: string[] | null,
	page: number | null,
	limit: number | null,
};

export type SearchQuestResult = {
	total: string,
	quests: Quest[],
};

export type UpdateQuestRequest = {
	title?: string | null,
	summary?: string | null,
	details?: string | null,
	status?: QuestStatus | null,
	techs?: string[] | null,
};

export type User = {
	userId: string,
	githubId: string,
	handle: string,
	createdAt: string,
};
