// This file has been generated by Specta. Do not edit this file manually.
export type CreateUserRequest = {
	githubId: string,
	username: string,
};

export type User = {
	id: string,
	githubId: string,
	username: string,
};
